Feature/dseat 31 improve design of individual bill page
re-motion/students-RubeesEat pull request #21
Opened 2024-09-09 09:55 UTC by IremA99

https://re-motion.atlassian.net/jira/software/projects/DSEAT/boards/17?selectedIssue=DSEAT-31

2024-09-10 10:58 UTC, KuJo7 approved these changes

2024-09-10 10:58 UTC, KuJo7 commented on RubeesEat/wwwroot/css/site.css
> +}
I think this hover effect should only apply to the entrylines in home and not on billdetails too since this is not clickable

2024-09-12 07:37 UTC, a-ctor requested changes
Please re-request once the other PR (which this one depends on) is merged. Please also rebase this branch to the top before re-requesting

2024-09-13 11:17 UTC, KuJo7 commented on RubeesEat/wwwroot/css/BillDetails.css
> +.billDetails{
I think we should get rid of the hover effect, because this indicates a button which is actually not the case

2024-09-17 07:23 UTC, a-ctor approved these changes

2024-09-17 07:35 UTC, merged