DSEAT-35 Implemented functionality to disable split bill add button a…
re-motion/students-RubeesEat pull request #28
Opened 2024-09-16 08:26 UTC by IremA99

https://re-motion.atlassian.net/jira/software/projects/DSEAT/boards/17?selectedIssue=DSEAT-35

2024-09-16 09:22 UTC, FelixSchoberRubi approved these changes

2024-09-16 09:26 UTC, FelixSchoberRubi requested changes
Wait for the branch for the remove button to be added, and then rebase this branch on main and adapt it so that removing a person enables the add button again

2024-09-18 08:19 UTC, FelixSchoberRubi approved these changes

2024-09-18 10:07 UTC, KuJo7 requested changes
Put the part for addPerson in a separate div with the id `AddPerson`:
```
    <div id="AddPerson">
        <label for="billPeople">Add Person:</label>
        <select name="billPeople" id="billPeople">
            @foreach (Person person in PersonRepository.GetAll())
            {
                <option value="@person.FirstName @person.LastName" data-id="@person.Id">@person.FirstName @person.LastName </option>
            }
        </select>
        <input id="addPersonButton" type="button" onclick="AddPerson()" value="Add Person"><br/>
    </div>
```

2024-09-18 10:07 UTC, KuJo7 commented on RubeesEat/wwwroot/js/SplitBill.js
> +    const dropdown = document.getElementById("billPeople");
```suggestion
    const dropdown = document.getElementById("billPeople");
    const AddPerson = document.getElementById("AddPerson");
```

2024-09-18 10:07 UTC, KuJo7 commented on RubeesEat/wwwroot/js/SplitBill.js
> +        dropdown.hidden = false;
```suggestion
        AddPerson.hidden = false;
```

2024-09-18 10:07 UTC, KuJo7 commented on RubeesEat/wwwroot/js/SplitBill.js
> +        dropdown.hidden = true;
```suggestion
        AddPerson.hidden = false;
```

2024-09-18 10:32 UTC, KuJo7 approved these changes

2024-09-18 12:24 UTC, a-ctor approved these changes

2024-09-19 11:14 UTC, merged