Feature/dseat 50 allow editing bills
re-motion/students-RubeesEat pull request #43
Opened 2024-10-16 07:50 UTC by IremA99

https://re-motion.atlassian.net/jira/software/projects/DSEAT/boards/17?selectedIssue=DSEAT-50

2024-10-17 13:39 UTC, FelixSchoberRubi requested changes

2024-10-17 13:39 UTC, FelixSchoberRubi commented on RubeesEat.IntegrationTests/PageObjects/BillDetailsPageObject.cs
> +    }
This function should be ClickEdit.
I just now got confused and thought this was the Update button inside the EditBill page.

2024-10-17 13:39 UTC, FelixSchoberRubi commented on RubeesEat.IntegrationTests/DB/DbBillRepositoryTest.cs
In InMemoryBillRepositoryTest you added a test for an invalid Bill, but here it is missing

2024-10-17 13:39 UTC, FelixSchoberRubi commented on RubeesEat/Pages/EditBill.cshtml
This file has a lot of similarities to SplitBill. Is there a way to avoid code duplication here? Maybe discuss with Lukas during standup

2024-10-17 13:39 UTC, FelixSchoberRubi commented on RubeesEat/wwwroot/js/editableBill.js
> +});
This has a lot of the same code as AddPerson. Maybe you can seperate the common code into AddPerson, and move the code that is specific into 2 other functions (so one function AddExistingEntrylines and one AddPersonByDropdown, which both use the AddPerson function for the code that is used in both)

2024-10-17 13:39 UTC, FelixSchoberRubi commented on RubeesEat/wwwroot/js/editableBill.js
> +
This function doesn't seem to be used anywhere

2024-10-17 13:39 UTC, FelixSchoberRubi commented on RubeesEat/Pages/EditBill.cshtml
> +                        }
```suggestion
@foreach (Person person in PersonRepository.GetAllActive().Except(currentBill.EntryLines.Select(entryLine => entryLine.Person).ToList()))
                        {
                            <option value="@person.FirstName @person.LastName" data-id="@person.Id">@person.FirstName @person.LastName </option>
                        }
```

2024-10-17 13:39 UTC, FelixSchoberRubi commented on RubeesEat/Model/DB/DbBillRepository.cs
> +
I think this is missing the exception for when a billid is not found

2024-10-17 13:39 UTC, FelixSchoberRubi commented on RubeesEat.IntegrationTests/Controllers/BillControllerTests.cs
Tests for the different Bad Requests for Update in BillController are missing

2024-10-17 13:39 UTC, FelixSchoberRubi commented on RubeesEat.IntegrationTests/SeleniumTests/EditBillSeleniumTests.cs
This should have the other tests that SplitBill has. Unless we find a way for the SplitBill and EditBill page to no longer have duplicated code, then we might be able to have less tests

2024-10-17 13:49 UTC, FelixSchoberRubi requested changes

2024-10-17 13:49 UTC, FelixSchoberRubi commented on RubeesEat.IntegrationTests/PageObjects/EditBillPageObject.cs
> +}
This is very similar to SplitBillPageObject. I think the only difference is which button can be pushed to submit.
We should create a more general PageObject Class, of which SplitBillPageObject and EditBillPageObject derive.
Or we can simply rename both buttons into submitBill. That way we only need one PageObject class which works for both

2024-10-24 08:06 UTC, a-ctor approved these changes

2024-10-24 08:31 UTC, KuJo7 commented on RubeesEat/Model/DB/DbBillRepository.cs
> +                command.ExecuteNonQuery();
We will do that in a different task (DSEAT-59)

2024-10-29 14:24 UTC, merged